spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lecture
    username: root
    password: 1q2w3e4r
    
mybatis:
  type-aliases-package: com.web.study.domain.entity
  mapper-locations:
  - /mappers/*.xml
  
jwt:
  secretKey: OrMyhF2YSVhywTzFlLwNmuuvO5gh83AkOrMyhF2YSVhywTzFlLwNmuuvO5gh83Ak
